add require 'timeout'
Fixes, test error with net-ssh 3.0.1 

 session that cannot authenticate adds host to exception message
      NameError: uninitialized constant Timeout